Changed the keyword (sleep)
Silvan85/Nova_SDS011 pull request #2
Opened 2023-04-12 21:55 UTC by DeltaC6

I was implementing the library in my project on ESP32 and I came across this problem. The library was not compiling due to the conflict with the keyword (sleep).

I have made the fix. Hope it will help others as well.

> Imp Note: To use this library with ESP32, you will need [EspSoftwareSerial](https://github.com/plerup/espsoftwareserial.git) library as well.

2023-04-13 05:56 UTC, Silvan85 requested changes
Pleas fallow suggested changes.

2023-04-13 05:56 UTC, Silvan85 commented on src/NovaSDS011.h
> +	_sleep = 0,
Pleas stick to one naming style for whole enum. 
Lets go with mode_sleep, mode_work, mode_work_error.

2023-04-21 18:56 UTC, DeltaC6 commented
I have made the requested change.

2023-04-23 11:12 UTC, Silvan85 approved these changes

2023-04-23 11:12 UTC, merged